sudo: false
os:
- linux
language: haskell
cabal: '2.4'
cache:
  directories:
  - "$HOME/.stack"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
- stack haddock
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
deploy:
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
- provider: hackage
  username: "$HACKAGE_USER"
  password: "$HACKAGE_PASSWORD"
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: sHgO7H5Q0PB6P3pG1yh6a51guAYPy6dkIfNLVY/ku/z4n9ZzE8j9txmZ6vz19oehw/vVW5PuGZaxQYv9822yQyYxQIlMYghx4IDwoh1mEc8jKrD6Q2SsiC3eSxcpdVYPD0EI3yNkozhipmJ9qRqOQCXJcioJKqXqFcdeNd4AsImjmE+yi6OfDE9Tw8+6Z/30kX2cxA1iFVWEgAYeqqyx+eI55XwIZF14Qcf4OJbIbVrjupb+nMN3avh3LrRFD0hjStWNKUrZkw54kgNVXr3QZ2zscx1MO1cqmbeZyXJ7r7dm15qEodsG9mlc91k3UlX/cZf2Hrh7NrQ8j0NHdZ2K16Jc2ND+uwD7x1xr24eGkYXWHnov24duJQmcb7irv3n3+mA0NnxSCR/GN2yRbw9kyPROft8C285/WVA50tozCG3k6ZBjIPBzW7c7ucvB7CamIqht5ueTmLUDQRsEu2SXFXxT58MfeiBCNQkJXplmUnU+MZaSMOG39VJA1fSW/rPsMCUwgLGgbUEOvI/kPYD81J8rJVbR/YGUAODmShXL8SSrWgJXqFf5D4hVD++5efmzOXbY7NwY8nwu8t3foo0eq8KBg95pBJNvEVDafsbJkBxfY/+u5knOI33xq43OOq1pa5oc1xxwvEX5Gqm5JWd5rCCQoVnwcSgnPZyTHm9up10=
  - secure: CnwWpmbuBlmb2WQ+kmDXExPfLmbmJfLp+64UTDHLjo9bUBq+eWcJbzZj0aeFMC4z0/KhHdMdGiOpC9IxxDyyGGaxSf6n1JTCwb5aTWyBLyJF3Tnejpdm49JxztBJpAW3hVxB0KKTkVIL0IHF+Uq5X0zW7s5ChuIszC/Vp51sQJf2OTY+0tHoyk4XdbwUebkCzRFnRBXgydhcnCJRpxRyvM3RJBZH7J5FWkOGh1Ln4jewNSqB7uIzvrlc2aZ6El7xAAxTCFkkL7gIDjfvDt0OxeC+m2L+z5cO4iVdSReU+dXTIM3madM78GpDooZGLN5C2nv7U//wiINAgUiGeCEtw4k9BzFF3UFAzaZhTgJgy3rfzTXxNmEoYdL4m2Bbtn3/OSlqAdXq5/c2MNHE/Jd3dnuA2BnQ50K4wxMUawX2u8bFJrW0i9YvZnUYFqw3ho3PAtNf0B00cdSKGpQ3h5kFxEl8+7zlIXUExP+vylf8DochgpZSg87X+4Q1892Clp0w1xgVJy4GwBaszWFzasNFwcVerw/8yFDGp+9hUrBbIowpk9NtQjKx9s8NevbmpXd0caup5JgzEybYjk/MG6MyxZ88Gm6HrwUwkCk6oFwKo2smooEtKKaWBotaGiXXO58usX9WjGMtiyaix6Wk5O1/i92GLOLjq8/Nz6fnNBw1ghY=
  - secure: se3HYLwzCew8WqleWCYJIn3TEHDGSS0ogm4j5e+9IEaUGk8RUyhhyME+O89EEqjzBeLwi8UuOwRJf3Wdw79xXqYz5JY962pYm6/aMHtSWuh6iLfrEPHR5sy9kM9MJTvsQ6SKogZLy3f2IJhRaf+6ZVlI5y+ovKUBOajZTfhuMMU40vVgUgqSY4JDNnds7qpoZS4Z0Ia215W+IVuETNMiXVyGHxQgz+fiRzPZPcDilFlV6cUqYQMK0VpQmwtIC+ZbJoUk3aYpJKnMo20u7jB3PTzjgiBwg7c1COcLYgPDF/Twp91ul1uleBmlhLo8WUymdjau3Y3Th/PtXNBAXdPm5NIHuipvpT/m589Tw/9pWvec0+wBZ+httw5TITsJ/sC6bmZKB43uaEqXC3z4SBve675v+eupZaQ549NbVD4MjFO/6YUBs1F1WaWlUNNwECe0RADd1CXh707KHk1ca1szknd+Vm4y+PLepNFfuaE/GrnpvDiVVFZj+MswCjwHmkyyUFKS7MKAP4KpHBSJPT4t8uK+Ch3d9K9qAM2QlD5D3ocru6uOfI8WHM7uROEwu2fCgd0NPYCWFEGVBH9lJZFX91Yih8g2A7EZ2wmpB4P+q9bWlSc4nxZbXSDVKxs84OduvfmrTUMOkCXmugrfn093ECSLZVi8MvNIVgUVcxK6Jxg=
