sudo: false
os:
- linux
language: haskell
cabal: '2.4'
cache:
  directories:
  - "$HOME/.stack"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
- stack haddock
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
deploy:
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
- provider: hackage
  username: "$HACKAGE_USER"
  password: "$HACKAGE_PASSWORD"
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    secure: DS5OIEMiK1/8rpz/DvSUKz+iVynWtjNB/je1kBAOToveRJCC+cEHuifRE3RViSg3s1T3B1Z3LfmVWK/rSf3z0fXvMTM4XeQl3pABep0xaUAMNf+oVnCm+ju29rljyHK+icBIC8ULzTdZZNx9CJ/GqnhEktpQ1ST1/gE3u2v4r72h+QWmIE6QvDZeJE/gL8+njwIM14TjIKFbo7uNyo3MpMyyKrGU32tZtbCDcHCXu5qYD2U8F9H/3AeYqAhCeGyfVHFMNg7FRwndGAiTt3CVtRMIZnVjOij8lc9hhEJwsmFDw3uWZs1j92FXpBzn9xlu9jQBrVIf1QSDnbrG/NHcknPe4oPNb2OkGK3Ntvz5hmBxa+PTjlsZP/4OUwsGQ4IS0jpeITvmNVB542zDTEkCUg20N9jOsstzFWaQXDhTBbc0EMLzfSTqrCpVIK2CYiFv2H8kE/6NfxuC6hk8heHQezjuzYePl7Atp7qFr0Jh0BEfJ+ddmMLTqXJwQ3HlgNuZpIU43TYCrDBPEqx+9QV0qEESdQhWh7wrxfFKSngfDHKlN2/SfUFlz075117MA99wVrw/B12JPBa/CBO5MG7Z/RSe1ZyuILhJpUxa91yQbTT27G3RMn/QZi7QXdlsj4FJNWnni6Cfuf161rzEIHhOy5cggSBoztNHGiYMHFfmh0k=
