sudo: false
os:
- linux
language: haskell
cabal: '2.4'
cache:
  directories:
  - "$HOME/.stack"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
- stack haddock
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
deploy:
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
- provider: hackage
  username: "$HACKAGE_USER"
  password: "$HACKAGE_PASSWORD"
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: vdvusDjz2j8oPaWNFcEc+UXwLwe0dQqyVr9QjIpQ7nFzjA3ibZ7oEwdwabpr3d62sj9T91B6CW0a6D0PdJJV+KmlfYZLPGq8+/G6AdjuD7i2qYSxP1oT9kIkgn3cLlhHky0PYHTGTfLmv9IAZ8+c2GgiDR4xmGPjUBFV4EBJ6bnPgPvyL6t9EeIZ+gkZXhPKf13D+98bllxiuhnZdjKFTWdXWEJ0zitJU5FLP6LAa5pWKekQL2O95x9F+4p56K//1aH6Cu6VHWnWzEAvx3w9n4ACwjGpKSTa9Ef6WJaIS15meXz+v+iOQxmdhX3mgte+zBv7YvO50RUL7htJlnMt9jzUFW2r3nJIOROF9a0mLYzy2vPgmySM3CMZQ8b/dN2ybeIexbSTilhE8OhzPvHXRK9L8b5VklkId8cWl38vgENP99EM+ypFmzIEI2KEj5Gl2mojvr9OxdX0t+zmMLZ6MuOdPZ2lKwZ3osyGd9pgF0v6lPw84LzhbuQ6LPaFmAu3DptqUzrocili/QAOyf0IkT48iEvk/rEKr+XTOUAwe24rHQZAu1zUt5jgUAqprSsr8aiFnZHXMG+9WYVKL7LYjzC8Nbe7A/mDJulMroRLaYRK/O/z7nD9Xq+rHzGHUQD8pJUdprAspKp7vTwleSGcFEep7qg3T1ilOnoz4AeM5yE=
  - secure: IOOVXaXnTJp6xliPGEeHCBNum5eChJLVYryOtZOE/wsQzHsYU3aJ1e+42clBcfE/HzDzvXOrFcknQvA/a93zZF548cs5hnvjoXHH36CiQCXL++TyWoJdCzh8/khIFgVyaizaDT+55TSXNB+wwiXAM/wuBkaYPR0Lg0+nJYrdItZO1nkDjRjUfhsbKtU3MEh9SmTv6khSx/S9IEMvyZacNJcSz7qvlBxQ3K//YXcNZeQTJ13XoaIZL3RP9QAuqFqBmekOJGrhWhrOcXSYFIQ5l/RgqmF/FR3uWQTzbOSDQfJpa2eFWbgom3IMeDGckth30L9Ahi2f5tjkGjvu+abn80tRb2p1Mc9O8IQFvtEATToV1sgMsDv2BhHkKzFCR14kEUUpLnW017tNWV+w0FmQA5c48r1Q10C3VkZj4RnXI9XC8EUFMUx3OikiFl4tagnVodZZ/+O0xm8W54EXN2YBk5JJgT++LORTzgSpjY7OsCSEG8BTpRwoMudodUZij6cnM+PrY8xfyKna4KasRx9uXSvj3UkHptzUCckOafLdlV/n29NE5YqGGFzhVOXKa3fyp6HbYQKHuZKXt8vysFVr9dCemI9vmQ1iWgGcQ3VM1LZiYZm0blFKs+fpuT82LfSHbRNu3CXaOAuCR3D6Qyy23uRO0yhzqRej/imdnBiGLT4=
  - secure: KjYUMsOvdbxzij9i9r6E8mVD/HLlMFxjOXW9pL/5nxUDeVf0StybKrhxjmDT5pIAelXicx/K/dA+2UEBpyzoHhB5dcXSDxhftfhOI9xqZDdQc+uQoc3Nm6SUTpFBwvCRHn2j+5cDNK0etM3y3Ph3z0FbQoOW2sf5/Tp06n2eLcIteGL9lZL4s6rpIkrjFmYwvUkVH/NzMYZeQXxnxALWMKzy69kGi4oEwhEvgm/ffKhS3kkLlowxvAMNtAU8DC2BnJbFmGJf7MR6kFi5phJWVsP2eFTGlOU6irq4jXxDRcydTThnmtaXSiA38Al7/kdt6KpNlI3v8qGbCAkZtra0pehQvTC92xkqmD7vgdUulHtICNxmiYV914hguYLdmP6eZgqjynUgf2cAvnA5pdsrVbxEPlFzoLcn9wUg9EkA+1Zx/z+M6cNParSSI3cyK3yo3F3L1Ps1wlyOWbg7T5vWrYwYkmhqnd95pN7M1oh3ED5SpTRyOjF8X41VStXDbOnde1rfS9mCoim+0MKH3y2LSsJBQyDcM+RmniUMfjxDGZVZg/2i4Xg2mU/99S4v9q9zYjOaKagkHkS9nTy0ziQbgKjVA8dmSkbxaMBLjG5eXcVp8UIaJrcLHiaG/egW6NWhfAZ+hEGovqg8qVRC+hgrJQ8uqItYe1K9en8+6B7zIDM=
