sudo: false
os:
- linux
language: haskell
cabal: '2.4'
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo add-apt-repository -y ppa:hvr/ghc
- sudo apt-get update
- sudo apt-get install cabal-install-3.0
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack build
- stack haddock
script:
- stack --no-terminal --skip-ghc-check test
- curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
deploy:
- provider: script
  script: bash deploy.sh "$HACKAGE_USER" "$HACKAGE_PASSWORD"
  on:
    tags: true
- provider: pages
  local_dir: "$(stack path --local-doc-root)"
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    tags: true
env:
  global:
  - secure: CnANBebJzvHlmRV1G0DvAyuNai7LJGtZLIa/QMgh09RU0SXQL0A3H23nG1DZ6tOzJ8PA2xGMJN8pWLbXVT62e2BU/k/ZtwRJRg36/QRx9dWMyjqboY3pWbppFkJA3FqZtN3uFKYJl6H8nVe4jatUnbBMBIIrL2taSPalHncmKTFH8pTHXE6UO24c6RAA0fgkHoc09Ej+FZxGX3os+w0UcMakZMy7r6usmWDxadslmS2/EeckeKONrG6ysJEy3bfRPw3pe/m1+2PZlDctomm5I3Xxi+xy7gg4/Crsx4bQOJ+P99mch2jN8cUqE8C08udXc3BksaIq5YRoAHt8TJtrpJs1JJzLGNZzRcBjR2sgBmyouO/RNo040SGQRcs0WDgxlbZasdDBcQpzapDSZGBReTTwEppJU3Bt9HbnxI2XeM85Nf6eGMBc9RDYjUluyyT77L/r9mT1CN5IjzrTxFy+5CtAsmZww9XXJwSTz6CJgqfXK/Sc7eCu1x0y7gibkPVj0LNR+Zjyq7JxxZTqCG2b1AGvX8U+EvUP5oGY035GEfiUPJLwEebfpz4j3qnGBi/6YJrOHqs9EIu+h1Ix/4v2nuIxAWfE0idwmREqSHe73MdwHtbSodH9VtgoDNrab8aVZcw73AzLjlaz5m7Te8LF5hkUJNsxO7db9iQADHY71VU=
  - secure: uEekxezssQ9uo72XHid92tU/6MV8yxvh8VHlnWh7d7yF1SMD3XnT92+1DBnD9FTwOBrOUDtmiDlI1wUQCyPd8fUyogKP5UGa4lJD4o3isDR5pIBAkTLlUhWfGbhjucyol9kPxrLcWHw9Kzy3nuGd7fkCU2rusY+2AQwnd+LhtQV4EAx4V7pbFHVYcxoWF1LW+rXOWwBUpQyXhdaXC+VaHDadjicQopncPMo2C22eirjhF7HqYmVBbZaelx6fjzGA3kUyhD9ulqK9wK8Pib7uhDT7B3/UhOPcHeHh4xBBCYkqAECd6QcI/2n3TO/A7+DtfJYlejpHOJvi1B6JM7w0ZCEoN5OH/7w0Rbmbd+Wo1XHhcuwZaYJDiBeRQNSarljIZjLrRXnxhJ8sbpO49bbPWoDPqqKAXK4rDYirHbBPb1LqkxJ53mlkMWLdMyKPQYjMDtFHWwmnk9NKwewepMPeYCQIxmYYJblOdCNkaUKmnDL3dug59JVwjVgMG6lfgSTAqx096j9uEdInNhmoxSfs3+R5OfCyfGkmm1+nw99PZrwpYgaXSFBPPt2dKieA3VTt/Q5caBxwyj67LFra5VvjWVT6366+FCps+GfrchFpiRJGOfvQ0EaHJwPhU83ayIkRz+u1/cyqqmgxk+Af9gd79CtwyRkfwrAwLatX4WrL+FI=
  - secure: LhmsBlESSgp/2CA8rxSuTCSLfRAVp8Mn1hTsUMD5S3lIiuT1RIdqTmCctIgIz6+BF2+m1q+v33QHnwM5kQ048wvtbzSCXl3Ic2aXB/8rtKf92QL6plha1oSjfHHuEJ4oEFW70xn5wE1vXmEAMYu/14cZEXuWXo5KY3dC7WQ6DANn5U+kYi3QWqlP4/zBSYvEC0hq5hy0NN/WN+asvsWav+IBLpQOoVQm+2E1GLviLAoWxXzU3FPj+n3Ovo7gl6nUbh6DWTMxCFp3PPhpKAPZ8tJJVRzr8l9XgW1jfmhDKTTjovGxHhDPdR6yrqQ7MpfQpakUOWCGcL3Sk//Ouw4sX/Ck3EO9mUJu7J72V5lqfW4/1MrN84ppC8sL8JzT+3A92QB4vAxNLs2U+4HKiTtt8jGCxSuMB4f3eW+sM0WaOydomu+d+nQL+sCKWy2wy4Wl7t181oNiSS5WIMq3dq128PoOtZezxADNenNV9btMkChUOyDb30CUsBYUywc/tsw60/mOrOFmo31D7pqMAQdBOPcUAMf+vjqu6hj+VSYCxF6B7YkrLgCO4psohQppmgVlpa3hSILhOX3EFHfyQ8IeFgfaJnstUPO9vcb++79VGFbQVT2Z4wQ5zwYRZeRrixyZrGGs1DSO8ZzB45xxd2qStgDOTXNEUgB24zrL98uZ2Qs=
